# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Holla' do

  use_frameworks!
  pod 'PureLayout'
  pod 'Dodo', '~> 7.0'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'

  pod 'OAuthSwift', '~> 1.0.0'
  pod 'KeychainSwift', '~> 7.0'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0' # or '3.0'
      end
    end
  end

end
